### PR TITLE
add footprint for Bourns PV36W

### PR DESCRIPTION
**Pull request by ppelleti**
This adds a footprint for the [Bourns PV36W potentiometer](http://www.bourns.com/docs/Product-Datasheets/pv36.pdf).

bourns-pv36

### CODE REVIEW

**Comment by poeschlr** [comment]
Nice footprint. But there are a few problems.
The distance between the bottom body outline and the pad centers is not quite right.
The courtyard clearance is all over the place. (should be 0.25 all around the part.)
Maybe include the cutout on bottom to make it more clear how the part should be placed.
pv36w

**Comment by ppelleti** [comment]
I've committed an update which should address these issues.

updated-pv36

**Comment by poeschlr** [comment]
Looks good now. I just noticed your 3d settings are off. Please change the scaling factors to equal 1 and it should be ready to merge. (Sorry i overlooked it last time around.)

**Comment by ppelleti** [comment]
Thanks, I've changed the scale to 1.  (I started from the existing potentiometers, and it looks like there was a lot wrong with them.)

**Comment by poeschlr** [comment]
Thanks for this great contribution.

**Pull request merged**
