### PR TITLE
Added Alps RK09, Alpha RV09 and Bourns PTV09

### PR DESCRIPTION
**Pull request by DavidMenting**
I've added a footprint for Alps', Alpha's and Bourns' smaller 9mm potentiometers.

### CODE REVIEW

**Comment by DavidMenting** [comment]
Bourns PTA6043 slide potentiometer added as well.

**Comment by pointhi** [comment]
* increase the anular ring of the pads, to be solderable.
* remove SilkScreen from Pads
* add SilkScreen outline to Bourns-PTA6043

adding a Fab layer would also be good idea (according to the new KLC)

**Comment by DavidMenting** [comment]
Will do. What is a recommended minimum annular ring size for hand soldering?

**Comment by andrew8er** [comment]
I enlarged the pads in the Alps RK09 package, you can cherry pick this commit and update this PR: 
https://github.com/andrew8er/KiCad-Potentiometers.pretty/commit/5f5e6d8e24e1a44ee550d09b16da4d097233b983

**Comment by jkriege2** [comment]
Please also add the component outlines to f.Fab (width: 0.1mm), change the width of the F.SilkS-lines to 0.12mm and add silkscreen to Bourns-PTA6043

best,
JAN

**Comment by andrew8er** [comment]
Would have added a f.Fab outline, if there was a way to copy lines to another layer. Is there something that I've missed?

**Comment by jkriege2** [comment]
As far as i know: unfortunately no, but you can edit the file with a text-editor directly ... that's fairly easy to do. When making the outline, please note that the silkscreen should be visible AFTER assembly, i.e. usually the silkscreen lines are a bit offset from the F.Fab-lines which are the exact outline. here's an example:

2016-12-04 22_59_49-footprinteditor keine aktive bibliothek


Best,
JAN

PS: Please also note our current effort to improve the KLCs (especially concerning explanations):
https://github.com/SchrodingersGat/kicad-library/wiki/KLC
https://github.com/KiCad/kicad-library/issues/879

**Comment by jkriege2** [comment]
This should be partly included in https://github.com/KiCad/Potentiometers.pretty/pull/16

**Comment by andrew8er** [comment]
Is renaming the footprint an option? Because the original name includes neither information on the type (vertical/horizontal, single/dual), nor is it specific enough. This footprint only applies to the RK09D and RK09K series, but Alps also has eg the RK09L series with a different footprint.

**Comment by evanshultz** [comment]
@DavidMenting 
I'm considering that you've abandoned this PR. Chime in if I'm wrong.

Here are images of these footprints:
image

As none are KLC compliant, and many are already in the library, I'll be closing this PR if I don't see any action in the next couple days.

**Comment by DavidMenting** [comment]
If the 9mm potentiometers are already in the library closing this PR is fine by me.

**Pull request closed without merging**
