### PR TITLE
Add footprint for Copal CT-6EP trimmers.

### PR DESCRIPTION
**Pull request by ppelleti**
[Datasheet is here.](https://www.nidec-copal-electronics.com/e/catalog/trimmer/ct-6.pdf)

I wasn't sure what the pin 1 marker should look like, since pin 1 is in the middle of the left side.  So I haven't added the pin 1 marker yet.

ct-6ep

### CODE REVIEW

**Comment by hackscribble** [comment]
Hi @ppelleti 

This style has been used on some recent PRs: chevron on fab layer, straight line on silk.

image

**Comment by hackscribble** [comment]
For the 6EP type, I think these two images from the datasheet mean that pin 2 needs to be at the top of the package rather than at the bottom (assuming pin 1 on the left).

image

(The view below is from the bottom, looking into the pins).

image

**Comment by ppelleti** [comment]
Thanks!  I corrected the position of pin 2, and then rotated the footprint so that pin 1 is still in the upper left.  I also added the pin 1 indicator as you suggested.

ct6ep-chevron

**Comment by hackscribble** [comment]
Thanks for the contribution.

**Pull request merged**
