### PR TITLE
Added horizontal placement of Potentiometer_Bourns_3296W_3

### PR DESCRIPTION
**Pull request by luftek**
3d model in pull request for modules\packages3d\Potentiometers.3dshapes

### CODE REVIEW

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: Potentiometer_Bourns_3296W_3_horizontal
  Violating Rule 10.3
    Keywords are separated by spaces.
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
```

**Comment by jkriege2** [comment]
Hi @luftek 
could you fix the above-mentioned KLC issues ... then I'll also merge your 3D model (https://github.com/KiCad/kicad-library/pull/460)!

JAN

**Comment by luftek** [comment]
O sorry, kind a forgot to to that. Will solve issues and check if it is still valid

**Comment by poeschlr** [comment]
@luftek what about the fixes?
Also we have a new library convention.
Main differences:
  - a outline on fab layer representing the outline of the part
  - second reference on fab layer (user text field with text %R)
  - 3d file path starts with $KISYS3DMOD

In other words: have a look at the new travis output.

**Comment by poeschlr** [comment]
Ok i can't reopen this to run travis again because the original submitter deleted their fork it seems. (Which would mean they are not interested in updating this.)

**Pull request closed without merging**
