### PR TITLE
Add Bourns PRS11S surface mount potentiometer

### PR DESCRIPTION
**Pull request by GyrosGeier**
Manufacturer recommended layout for PRS11S

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi,

Please remove the "GLUE" pad, add the courtyard, fill the Doc and Keywords parameters.

Thanks!

**Comment by GyrosGeier** [comment]
Sure, will do. I'm not sure about the "GLUE" pad -- the datasheet says that this part can be glued to the PCB for better mechanical stability, so it would make sense to include that in the footprint.

**Comment by CarlPoirier** [comment]
True but that is up to the user to add it in. Glue is not included in
KiCad's libraries by default.

**Comment by GyrosGeier** [comment]
That seems cumbersome -- would it make sense to have two variants of the footprint (I use the variant with glue because I have knobs sticking out of the enclosure)?

**Comment by CarlPoirier** [comment]
I suggest you maintain the footprint with glue in a project-specific
library.

**Comment by michal777** [comment]
If the glue must be used, even if it's reflow soldering and its pattern is known, maybe it should be allowed? The main reasons for not using glue were: it's mainly used in wave soldering (less popular, more difficult) and it was hard to determine how much glue should be applied.

**Comment by CarlPoirier** [comment]
In this case, please add it as a a graphic item such as with the resistor arrays in Resistors_SMD.pretty.

**Comment by GyrosGeier** [comment]
Okay, can do that.

**Comment by GyrosGeier** [comment]
Should I leave the "attachment only" pads as pads, or also replace them?

**Comment by CarlPoirier** [comment]
Yes they are fine.

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by hackscribble** [comment]
Re-opening.

**Comment by hackscribble** [comment]
Hi @GyrosGeier 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
