### PR TITLE
Add EVM3* trimmers

### PR DESCRIPTION
**Pull request by yaqwsx**
This PR is based on discussion in KiCad/Resistors_SMD.pretty#12

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

first of all: THanks for the contribution!
Second: there are seveal KLC issues to be fixed:

```
checking module: Potentiometer_Trimmer-EVM3E
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.

checking module: Potentiometer_Trimmer-EVM3S_R
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
```
Could you fix those?

Especially: The Courtyard should be around the silkscreen ... I would propose something like this:
2016-10-22 17_47_32-footprinteditor keine aktive bibliothek

Best,
JAN

**Comment by yaqwsx** [comment]
Thank you for the response, I'll fix it - just one question; doesn't the cross in the middle break the KLC rules?

**Comment by jkriege2** [comment]
Hhmmm ... yes you're right ... but on the other hand that makes putting the parts on the  PCB easier, as you see (roughly) how the part should look ... I think we also have markings like that in e.g. diode symbol ...

@pointhi @CarlPoirier @diggit @SchrodingersGat : WHat do you think?

Best,
JAN

**Comment by diggit** [comment]
Silkscreen under parts is problem, because non flat surface can make them tilt. Probably not big problem for lifted parts and THT, but still, avoid it.

**Comment by yaqwsx** [comment]
In that case I think I already fixed all the issues.

**Comment by jkriege2** [comment]
THanks for the contribution again!

**Pull request merged**
